[build]
  base = "/"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_SERVER_URL = "https://reapers-whispers-backend.onrender.com"
  REACT_APP_SOCKET_URL = "wss://reapers-whispers-backend.onrender.com"
