services:
  - type: web
    name: reapers-whispers-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://reapers-whispers.netlify.app
    autoDeploy: true
